a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))
d = int(input("d: "))
print(f"Sum of a, b and d: {a + b + d}")
print(f"Product of all numbers: {a * b * c * d}")
print(f"The sum of a and b times the sum of c and d: {(a + b) * (c + d)}")
print(f"a divided by d (int): {a // d}")
print(f"a divided by d (float): {a / d}")
print(f"Remainder of a divided by b: {a % b}")
print(f"c to the power of -a: {c ** (-a)}")
print(f"b to the power of 1/2 (square root): {b ** (1/2)}")
complex_equation = (b/3) * (b ** (a + d/2) - 1) + c
print(f"Complex equation: {complex_equation}")
